### ISSUE TITLE
exponentialDelay doesnt work.

### ISSUE THREAD

**Issue by lawloretienne** [Rabsztok/ontology-tree-viewer#2]
I tried to set up exponential delay as you have done here
https://github.com/Rabsztok/ontology-tree-viewer/blob/138edce9d10e83962a93353c9345e2b7df8a09cc/src/utils/api_client.js#L10

but i get the following error

src/index.ts(44,61): error TS2339: Property 'exponentialDelay' does not exist on type 'IAxiosRetry'.

Does this happen for you as well?  Im using the same version of `axios-retry` that you are using : 
`    "axios-retry": "^3.1.1"`

**Comment by Rabsztok** [comment]
Check out https://github.com/softonic/axios-retry/issues/58
AxiosRetry in recent version has outdated .ts file. Without type checking, it should run fine, as `exponentialDelay` is implemented in 3.1.1.
You may use `master` branch of axios-retry, implement your own types or opt-out of type checking for that library.
